
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr8Z6MB9RRAWyZ_lDxSHpCO5B82ysPkvk',
    appId: '1:356593303198:web:5eb748ee4a27645fae458f',
    messagingSenderId: '356593303198',
    projectId: 'flutter-chat-app-78cd4',
    authDomain: 'flutter-chat-app-78cd4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-78cd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxLcP-kzGStodLCUetYAZJZotrNzdHAp8',
    appId: '1:356593303198:android:52fefbdd1a46baedae458f',
    messagingSenderId: '356593303198',
    projectId: 'flutter-chat-app-78cd4',
    storageBucket: 'flutter-chat-app-78cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR_VVrGmPP9EkIDbZDLXfrLqEy3xqqvyQ',
    appId: '1:356593303198:ios:a0e7bae66f66a8e4ae458f',
    messagingSenderId: '356593303198',
    projectId: 'flutter-chat-app-78cd4',
    storageBucket: 'flutter-chat-app-78cd4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR_VVrGmPP9EkIDbZDLXfrLqEy3xqqvyQ',
    appId: '1:356593303198:ios:a0e7bae66f66a8e4ae458f',
    messagingSenderId: '356593303198',
    projectId: 'flutter-chat-app-78cd4',
    storageBucket: 'flutter-chat-app-78cd4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr8Z6MB9RRAWyZ_lDxSHpCO5B82ysPkvk',
    appId: '1:356593303198:web:0ea86f42a12745f3ae458f',
    messagingSenderId: '356593303198',
    projectId: 'flutter-chat-app-78cd4',
    authDomain: 'flutter-chat-app-78cd4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-78cd4.appspot.com',
  );
}
